name: Vercel Preview Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

  prettier:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: npm install
          npm run prettier

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: npm install
          npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [prettier, lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
